---
- hosts: localhost
  tasks:
    - ec2:
        key_name: default-ec2
        instance_type: t2.micro
        image: ami-0ae8f15ae66fe8cda
        region: us-east-1
        #count: 1
        exact_count: 2
        count_tag: {type: http}
        vpc_subnet_id: subnet-0013aeb3f818fe4d8
        assign_public_ip: yes
        group: ["launch-wizard-1"]
          instance_tags: {type: http, Environment: QA}
          wait: yes
        register: ec2_output
    - debug: var=ec2_output